name: Release Docker

on:
  release:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: sherryyc
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.GITHUB_WORKSPACE }}
        file: ${{ env.GITHUB_WORKSPACE }}/Dockerfile
        tags: sherryyc/todo:latest
        push: true
    
